import { requireRole } from "@/lib/auth";
import { fetchAdminInsights } from "@/lib/actions/ai";
import { BarChart3, TrendingUp, Calendar, ShoppingCart } from "lucide-react";

export default async function InsightsPage() {
  await requireRole(["ADMIN"]);
  const result = await fetchAdminInsights();

  return (
    <div>
      <h1 className="mb-6 flex items-center gap-2 text-2xl font-semibold tracking-tight text-[hsl(var(--foreground))]">
        <BarChart3 className="h-7 w-7 shrink-0" aria-hidden />
        AI Insights
      </h1>
      <p className="mb-6 text-sm text-[hsl(var(--muted-foreground))]">
        Aggregated from your library data. Insights are generated by AI from real statistics only.
      </p>
      {!result.success ? (
        <p className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] py-8 text-center text-[hsl(var(--muted-foreground))]">
          {result.error}
        </p>
      ) : (
        <div className="space-y-6">
          <section className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-sm">
            <h2 className="flex items-center gap-2 text-sm font-medium text-[hsl(var(--muted-foreground))]">
              <TrendingUp className="h-4 w-4 shrink-0" aria-hidden />
              Popular genres
            </h2>
            <p className="mt-2 text-[hsl(var(--foreground))]">{result.data.popularGenres || "—"}</p>
          </section>
          <section className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-sm">
            <h2 className="flex items-center gap-2 text-sm font-medium text-[hsl(var(--muted-foreground))]">
              <Calendar className="h-4 w-4 shrink-0" aria-hidden />
              Borrow patterns
            </h2>
            <p className="mt-2 text-[hsl(var(--foreground))]">{result.data.borrowPatterns || "—"}</p>
          </section>
          <section className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-sm">
            <h2 className="flex items-center gap-2 text-sm font-medium text-[hsl(var(--muted-foreground))]">
              <ShoppingCart className="h-4 w-4 shrink-0" aria-hidden />
              Suggested acquisitions
            </h2>
            <p className="mt-2 text-[hsl(var(--foreground))]">{result.data.suggestedAcquisitions || "—"}</p>
          </section>
        </div>
      )}
    </div>
  );
}
