/** Predefined book genres so dropdowns always have many options, even with few books in the DB. */
export const PREDEFINED_GENRES = [
  "Fiction",
  "Non-Fiction",
  "Science Fiction",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Romance",
  "Historical Fiction",
  "Biography",
  "Autobiography",
  "Memoir",
  "Self-Help",
  "Business",
  "History",
  "Science",
  "Technology",
  "Philosophy",
  "Religion",
  "Politics",
  "Travel",
  "Cooking",
  "Health",
  "Psychology",
  "Education",
  "Children",
  "Young Adult",
  "Horror",
  "Comedy",
  "Drama",
  "Poetry",
  "Short Stories",
  "Literary Fiction",
  "Crime",
  "Adventure",
  "Action",
  "Graphic Novel",
  "Comics",
  "Reference",
  "Art",
  "Music",
  "Sports",
  "True Crime",
  "Essays",
  "Other",
] as const;

export type PredefinedGenre = (typeof PREDEFINED_GENRES)[number];
